### PR TITLE
Remove route to user profile edit page

### PR DESCRIPTION
**Pull request by richtier**
There are no editable fields on the user for alpha. Removing url for now. Post-alpha will reinstate once there is functionality there.

### CODE REVIEW

**Comment by konradko** [comment]
👍 to what Monika says. Unused code should always be deleted, so please remove the view code as well (you can always go back in git history and bring it back).

**Comment by konradko** [comment]
@richtier should this be merged? Has conflicts

**Comment by konradko** [comment]
@richtier this should be closed right

**Comment by richtier** [comment]
@konradko should not be closed :)

**Pull request merged**
