### PR TITLE
added 'next' text to form process and 'register' text to final step

### PR DESCRIPTION
**Pull request by franciscobenedict**
[this task](https://uktrade.atlassian.net/browse/ED-158)

- added 'next' text to form process and 'register' text to final step

todo: 

 - [ ] add tests
screen shot 2016-10-12 at 12 55 43
screen shot 2016-10-12 at 12 56 19

### CODE REVIEW

**Comment by richtier** [comment]
@monikasulik circle ci will show us if the tests fail if we read the log - so as long as we read the log we can be confident to merge :)

**Comment by monikasulik** [comment]
@richtier I know - the problem is at the moment reading the log says tests are failing, worse still - failing on master. Personally, I like the rule that when tests are failing on master nobody merges anything (otherwise it gets more difficult to debug and more likely that we bring in further failures and bugs).

**Comment by richtier** [comment]
tests passed 
image

**Comment by richtier** [comment]
@monikasulik as discussed IRL, in future the person reviewing the change will also check the test passes on cirlce ci by reading the log.

**Pull request merged**
