### PR TITLE
add line truncation

### PR DESCRIPTION
**Pull request by franciscobenedict**
[this task](https://uktrade.atlassian.net/browse/ED-348) and (https://uktrade.atlassian.net/browse/ED-349)

- added truncation styling to both company name/title and url
- added generic 1, 2 and 3 three line truncation for general use

### CODE REVIEW

**Comment by richtier** [comment]
the company name is tiny

image

https://www.youtube.com/watch?v=Gj4-E5Hs3Kc

**Comment by richtier** [comment]
does not look great on mobile

image

**Comment by richtier** [comment]
ah it also truncates the 'external link' icon

image

**Comment by monikasulik** [comment]
https://docs.djangoproject.com/en/1.10/ref/templates/builtins/#truncatechars
Not sure if this is of use or not, but just sayin'

**Comment by franciscobenedict** [comment]
Doh! I kind of did this one blind. My env doesn't work to this point so I sort of did it blind. Needs to take font size into account for the company name. Easy fix.

As for the external link, fix would b to wrap the actual URL in a span and apply the truncate class to the span instead to the icon remains intact. Generic truncation will come in useful here. I'll do it first thing in the A.M.

**Comment by richtier** [comment]
@monikasulik we need the truncation to be responsive: so when there are 320px available (on mobile) we will only show like 20 chars, but then there is over 960px available (desktop) we will show many more (like 100)

**Comment by monikasulik** [comment]
ah, @richtier thanks for the explanation :)

**Comment by richtier** [comment]
does not look great on desktop:

image

nor on mobile/tablet:

image

**Comment by franciscobenedict** [comment]
@richtier Thos changes have been made. Working blind will do that to a person.
- Looks great on desktop
- equally awesome on mobile/tablet
- truncation does works on tablet/mobile for both company name and url link 
- external link icon is inline with the url link also in all views

See evidence below (I still worked blind so I'll need to double check this once this is available on the dev playground)

screencapture-ui-trade-great-dev-8001-1478643213486
screencapture-ui-trade-great-dev-8001-1478643260964
screencapture-ui-trade-great-dev-8001-1478643287771
screencapture-ui-trade-great-dev-8001-1478643305905

**Comment by richtier** [comment]
this is what it looks like on desktop:
image
not good. I see you've given the title and the website 50% each. I would expect company name to get at least 75% of the room.
___
this is what we see with long name:
image
For consistency with the rest of the page I would expect the title to be constrained by one line, not spanning two lines. 
___

it looks fine on desktop, albeit affected by the 'title spans multiple lines' problem.
___

**Comment by franciscobenedict** [comment]
Desktop, table and mobile mode.
One line truncation used for both company name and URL. a little confusing since on the ticket suggests two lines for the company.

screen shot 2016-11-09 at 11 28 23
screen shot 2016-11-09 at 11 28 32
screen shot 2016-11-09 at 11 28 11

**Comment by richtier** [comment]
on desktop the bottom of the text is chopped off:

image

**Pull request merged**
